const IMG={kunafa:'https://images.unsplash.com/photo-1761828122856-8703baac8e86?w=900&q=86&auto=format&fit=crop',pistachio:'https://images.unsplash.com/photo-1778447830669-8fe9626ed738?w=900&q=86&auto=format&fit=crop',chocolate:'https://images.unsplash.com/photo-1559989399-c024c86f0404?w=900&q=86&auto=format&fit=crop',mango:'https://images.unsplash.com/photo-1620878439728-a8f735a95e3f?w=900&q=86&auto=format&fit=crop',mangoIce:'https://images.unsplash.com/photo-1681285317274-b75abafc67e0?w=900&q=86&auto=format&fit=crop',cookie:'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=900&q=86&auto=format&fit=crop',ice:'https://images.unsplash.com/photo-1557142046-c704a3adf364?w=900&q=86&auto=format&fit=crop',coffee:'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?w=900&q=86&auto=format&fit=crop'};
const products=[
{id:1,n:'كنافة محشية قشطة',d:'كنافة دافئة بقوام مقرمش وحشوة قشطة ناعمة.',p:12,c:'الكنافة',i:IMG.kunafa,cal:460},
{id:2,n:'كنافة قشطة بالكندر',d:'قشطة كريمية وصوص كندر فوق كنافة ساخنة.',p:20,c:'الكنافة',i:IMG.chocolate,b:true},
{id:3,n:'كنافة محشية بستاشيو',d:'حشوة فستق غنية بطابع ناعم وحلاوة متوازنة.',p:22,c:'الكنافة',i:IMG.pistachio,cal:450},
{id:4,n:'كنافة محشية نوتيلا',d:'كنافة مقرمشة بحشوة شوكولاتة دافئة.',p:22,c:'الكنافة',i:IMG.chocolate,cal:680},
{id:5,n:'كنافة محشية لوتس',d:'قوام الكنافة مع نكهة لوتس كراميلية واضحة.',p:22,c:'الكنافة',i:IMG.cookie,cal:620},
{id:6,n:'كنافة قشطة وجبن سائل',d:'قشطة وجبن سائل في حشوة ناعمة بطابع أغنى.',p:20,c:'الكنافة',i:IMG.kunafa,cal:480},
{id:7,n:'سجنتشر بستاشيو',d:'حلى كريمي بطعم فستق غني ولمسة سكره الخاصة.',p:23,c:'سجنتشر',i:IMG.pistachio,cal:950},
{id:8,n:'سجنتشر مانجو',d:'مانجو كريمي بطابع منعش ونهاية استوائية.',p:23,c:'سجنتشر',i:IMG.mango,cal:950},
{id:9,n:'سجنتشر لوتس',d:'حلى لوتس كريمي بنكهة كراميلية غنية.',p:23,c:'سجنتشر',i:IMG.cookie,cal:950},
{id:10,n:'سجنتشر كيندر',d:'شوكولاتة كريمية بطابع غني ومريح.',p:23,c:'سجنتشر',i:IMG.chocolate,cal:950,b:true},
{id:11,n:'أساور الكنافة',d:'أساور كنافة صغيرة محشوة ومناسبة للمشاركة.',p:18,c:'الحلا',i:IMG.kunafa,cal:880},
{id:12,n:'كيكة الكوكيز',d:'كيكة طرية بقطع كوكيز الشوكولاتة وقوام غني.',p:19.2,old:24,c:'الحلا',i:IMG.cookie,cal:1550,b:true},
{id:13,n:'عش البلبل',d:'حلا شرقي غني بقوام مقرمش وتقديم مناسب للمشاركة.',p:54,old:60,c:'الحلا',i:IMG.pistachio},
{id:14,n:'آيسكريم شوكولاتة',d:'كوب آيسكريم شوكولاتة.',p:4,c:'آيسكريم',i:IMG.ice},
{id:15,n:'آيسكريم كراميل',d:'كوب آيسكريم كراميل.',p:4,c:'آيسكريم',i:IMG.ice},
{id:16,n:'آيسكريم شمام',d:'كوب آيسكريم شمام.',p:4,c:'آيسكريم',i:IMG.mangoIce},
{id:17,n:'آيسكريم فانيليا',d:'كوب آيسكريم فانيليا.',p:4,c:'آيسكريم',i:IMG.ice},
{id:18,n:'قهوة سعودية بالهيل',d:'قهوة سعودية ساخنة بالهيل ومناسبة مع الحلا.',p:6.4,old:8,c:'قهوة',i:IMG.coffee,cal:2,b:true}
];
const meta={الكنافة:['الأصل','طبقات مقرمشة، قلب غني، وتوازن محسوب في كل لقمة.'],سجنتشر:['توقيع سكره','خلطاتنا الأكثر شخصية، صنعت لتكون أول ما تتذكره.'],الحلا:['للمشاركة','اختيارات أكبر للحظات الطويلة والجلسات التي تستحق زيادة.'],آيسكريم:['خفيف وبارد','نهاية بسيطة وباردة بعد جرعة الحلا.'],قهوة:['توازن اللحظة','قهوة سعودية بالهيل تكمل الحلا بدون أن تنافسه.']};
const cats=['الكل',...Object.keys(meta)];let active='الكل',selected=null,qty=1,cart=[];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const sar=v=>new Intl.NumberFormat('ar-SA',{style:'currency',currency:'SAR',maximumFractionDigits:2}).format(v);
function restaurantStatus(){const now=new Date(new Date().toLocaleString('en-US',{timeZone:'Asia/Riyadh'}));const m=now.getHours()*60+now.getMinutes();const open=m>=840||m<120;$('#statusText').textContent=open?'مفتوح الآن':'مغلق الآن';$('#visitStatus').textContent=open?'مفتوح الآن':'مغلق الآن';$('#statusHelp').textContent=open?'نستقبل طلبك الآن عبر واتساب.':'يمكنك تجهيز طلبك المسبق.';$$('.dot').forEach(d=>d.classList.toggle('open',open));}
function renderFeatured(){const f=products.filter(x=>x.b).slice(0,3);$('#featuredGrid').innerHTML=f.map(x=>`<button class="feature-card" data-id="${x.id}"><img src="${x.i}" alt="${x.n}"><div class="feature-content"><small>◆ الأكثر طلبًا</small><h3>${x.n}</h3><p>${x.d}</p><b>${sar(x.p)}</b></div></button>`).join('');}
function renderTabs(){$('#tabs').innerHTML=cats.map(c=>`<button class="${c===active?'active':''}" data-cat="${c}">${c}</button>`).join('');}
function productHTML(x){return `<article class="product" data-id="${x.id}"><div class="product-img"><img src="${x.i}" alt="${x.n}" loading="lazy"></div><div class="product-copy"><h4>${x.n}</h4><p>${x.d}</p>${x.cal?`<small>${x.cal.toLocaleString('ar-SA')} سعرة</small>`:''}</div><div class="price">${x.old?`<del>${sar(x.old)}</del><br>`:''}<b>${sar(x.p)}</b></div><button class="plus" aria-label="اختيار ${x.n}">+</button></article>`}
function renderMenu(){const use=active==='الكل'?Object.keys(meta):[active];$('#menuGroups').innerHTML=use.map(c=>`<section class="menu-group"><div class="group-title"><div><small>${meta[c][0]}</small><h3>${c}</h3></div><p>${meta[c][1]}</p></div><div class="product-list">${products.filter(x=>x.c===c).map(productHTML).join('')}</div></section>`).join('');}
function openProduct(id){selected=products.find(x=>x.id===+id);qty=1;$('#modalImage').src=selected.i;$('#modalImage').alt=selected.n;$('#modalCategory').textContent=selected.c;$('#modalName').textContent=selected.n;$('#modalPrice').textContent=sar(selected.p);$('#modalDesc').textContent=selected.d;$('#modalNote').value='';$('#qtyValue').textContent='١';updateAddTotal();openLayer('productLayer');}
function updateAddTotal(){$('#qtyValue').textContent=qty.toLocaleString('ar-SA');$('#addTotal').textContent=sar(selected.p*qty)}
function openLayer(id){document.body.style.overflow='hidden';$('#'+id).classList.add('open');$('#'+id).setAttribute('aria-hidden','false')}
function closeLayer(id){$('#'+id).classList.remove('open');$('#'+id).setAttribute('aria-hidden','true');document.body.style.overflow=''}
function addSelected(){const note=$('#modalNote').value.trim();const key=selected.id+'|'+note;const same=cart.find(x=>x.key===key);if(same)same.q+=qty;else cart.push({...selected,q:qty,note,key,ci:Date.now()+Math.random()});closeLayer('productLayer');renderCart();toast();}
function renderCart(){const count=cart.reduce((a,x)=>a+x.q,0),total=cart.reduce((a,x)=>a+x.p*x.q,0);$('#bagCount').textContent=count;$('#mobileCount').textContent=count;$('#mobileTotal').textContent=sar(total);$('#mobileCart').classList.toggle('hidden',count===0);$('#cartTotal').textContent=sar(total);$('#cartFoot').style.display=count?'block':'none';$('#cartItems').innerHTML=count?cart.map(x=>`<article class="cart-row" data-ci="${x.ci}"><img src="${x.i}" alt=""><div><h4>${x.n}</h4>${x.note?`<p>“${x.note}”</p>`:''}<div class="cart-bottom"><div class="mini-qty"><button data-act="minus">−</button><span>${x.q.toLocaleString('ar-SA')}</span><button data-act="plus">+</button></div><b>${sar(x.p*x.q)}</b></div></div></article>`).join(''):`<div class="empty"><div><b>السلة فاضية.</b><br><br>ابدأ من الأكثر طلبًا أو استعرض المنيو.</div></div>`;}
function toast(){$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function checkout(){if(!cart.length)return;let msg='السلام عليكم، أرغب في طلب من كنافة سكره:\n\n';cart.forEach((x,i)=>{msg+=`${i+1}) ${x.n}\nالكمية: ${x.q}\nالسعر: ${sar(x.p*x.q)}\n`;if(x.note)msg+=`ملاحظة: ${x.note}\n`;msg+='────────────\n'});msg+=`\nالإجمالي: ${sar(cart.reduce((a,x)=>a+x.p*x.q,0))}\n\nأرجو تأكيد التوفر وطريقة الاستلام/التوصيل.`;window.open('https://wa.me/966570207432?text='+encodeURIComponent(msg),'_blank')}
document.addEventListener('click',e=>{const f=e.target.closest('.feature-card,.product');if(f)return openProduct(f.dataset.id);const t=e.target.closest('[data-cat]');if(t){active=t.dataset.cat;renderTabs();renderMenu();return}if(e.target.id==='plusQty'){qty++;updateAddTotal()}if(e.target.id==='minusQty'){qty=Math.max(1,qty-1);updateAddTotal()}if(e.target.id==='addProduct')addSelected();if(e.target.id==='openCart'||e.target.id==='mobileCart')openLayer('cartLayer');if(e.target.id==='checkout')checkout();const cl=e.target.closest('[data-close]');if(cl)closeLayer(cl.dataset.close==='cart'?'cartLayer':'productLayer');const row=e.target.closest('.cart-row');const act=e.target.dataset.act;if(row&&act){const item=cart.find(x=>x.ci==row.dataset.ci);if(act==='plus')item.q++;else item.q--;if(item.q<=0)cart=cart.filter(x=>x!==item);renderCart();}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeLayer('productLayer');closeLayer('cartLayer')}});renderFeatured();renderTabs();renderMenu();renderCart();restaurantStatus();setInterval(restaurantStatus,60000);